OPR-184: Add sharing of sage visualisation for panel samples
hartwigmedical/scripts pull request #93
Opened 2024-12-30 16:19 UTC by LiekeSchoenmaker

2024-12-31 09:10 UTC, edk360 requested changes
Ziet er goed uit, alleen de directory zal iets anders zijn waar de html file vandaan komt.

Verder heb ik geen opmerkingen

```
gsutil cp gs://panel-vis-files/recon-cnv/${tumor_sample_barcode}/*.reconCNV.html gs://targeted-pipeline-output-prod-1/${set}/reporting
```
moet vervangen door:

```
gsutil cp gs://panel-vis-files/recon-cnv/${tumor_sample_barcode}/recon-cnv/*.reconCNV.html gs://targeted-pipeline-output-prod-1/${set}/reporting
```
Er staat twee voorbeeld samples in de bucket voor eventuele testen.

2024-12-31 09:52 UTC, LiekeSchoenmaker commented
@edk360; weet je dit zeker? De 2 test samples hebben de volgende locatie:

_gs://panel-vis-files/recon-cnv/${tumor_sample_barcode}/recon-cnv/*.reconCNV.html_

2025-01-02 08:05 UTC, edk360 commented
@LiekeSchoenmaker De locatie die in je comment noemt klopt, maar die klopt niet met de code in de laatste commit ( er mist een recon-cnv subfolder achter de ${tumor_sample_barcode} folder. Zie regel 18 van het script.

2025-01-02 08:38 UTC, LiekeSchoenmaker commented
@edk360; Ik zie het nu, heb het aangepast

2025-01-03 09:41 UTC, julianvantoledo approved these changes

2025-01-27 12:11 UTC, merged